# Configuración básica para al-folio
title: "Mi Portafolio"  # Añade un título aquí
description: "Descripción breve de mi portafolio"  # Añade una descripción aquí
url: "https://5nzalo.github.io"  # Cambia esto a tu nombre de usuario de GitHub
baseurl: ""  # Asegúrate de que esté vacío
